### ISSUE TITLE
MainComponent.java： es.amarinag.mvvm_databinging_dagger2.ui.viewmodel.GithubViewModel cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method. This type supports members injection but cannot be implicitly provided.

### ISSUE THREAD

**Issue by softboy99** [AMarinaG/sample-mvvm-retrofit-dagger-databinding#2]
Error:(18, 8) : es.amarinag.mvvm_databinging_dagger2.ui.viewmodel.GithubViewModel cannot be provided without an @Inject constructor or from an @Provides- or @Produces-annotated method. This type supports members injection but cannot be implicitly provided.
es.amarinag.mvvm_databinging_dagger2.ui.viewmodel.GithubViewModel is injected at
es.amarinag.mvvm_databinging_dagger2.ui.fragment.GithubFragment.githubViewModel
es.amarinag.mvvm_databinging_dagger2.ui.fragment.GithubFragment is injected at
es.amarinag.mvvm_databinging_dagger2.di.component.MainComponent.inject(fragment)

**Comment by Bhavdip** [comment]
Hi, I am running the same problem and found that `OkHttpInterceptorsModule` have two methods that return the List type of `List<interceptor>`. The same module` OkHttpInterceptorsModule` has been including inside the `Network module` While dagger is creating ` OkHttpClient` method with input as List type it throws this error. Because It should return Object may be something else. But this is a cause its show compile time error.

**Comment by Bhavdip** [comment]
Is there any idea? we can inject list as a parameter from another module.

**Comment by Bhavdip** [comment]
Right now I fix this problem as below:

  ```
 @Provides
  @AppScope
  public OkHttpClient provideOkHttpClient(Cache cache,
      HttpLoggingInterceptor httpLoggingInterceptor,
      HeaderRequestInterceptor headerRequestInterceptor, OkLogInterceptor okLogInterceptor) {

    //Http client
    final OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder();

    //Basic Interceptors
    okHttpBuilder.addInterceptor(headerRequestInterceptor);
    okHttpBuilder.addInterceptor(httpLoggingInterceptor);
    okHttpBuilder.addInterceptor(okLogInterceptor);

    okHttpBuilder.cache(cache);

    //OkHTTP read write and connection Timeout
    okHttpBuilder.readTimeout(30, TimeUnit.SECONDS);
    okHttpBuilder.writeTimeout(30, TimeUnit.SECONDS);
    okHttpBuilder.connectTimeout(30, TimeUnit.SECONDS);

    //return okHttp Client
    return okHttpBuilder.build();
  }
```
Instead of list I replace with the object as parameter.
